language: java

jdk:
  - oraclejdk8

install:
  - npm install
  - npm install -g grunt-cli
  - grunt build
  - mvn install -DskipTests=true

script:
  - mvn test
  - mvn --batch-mode -Dtag=v0.1.0-SNAPSHOT release:prepare release:perform -DreleaseVersion=0.1.0-SNAPSHOT -DdevelopmentVersion=0.1.0-SNAPSHOT
